version: "3.5"
services:
  usermanagement:
          image: bec0413/cmp_usr_mng:tagVersion
          ports:
            - "8085:8085"
          container_name: usermng-api
          links:
            - usermongo_db
          depends_on:
            - usermongo_db
          networks:
            - shared-net
            
  usermongo_db:
          image: 'mongo:4.4.6'
          ports:
            - "27017:27017"
          container_name: usermongo_db
          volumes:
            - /home/sinoed/data/db:/data/db
          networks:
             - shared-net
networks:
   shared-net:
      name: my-network
      driver: bridge   
          
